[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.build]
cmds = [
    "dotnet publish -c Release -o dotnet-out"
    # (You can add "ls -l dotnet-out" if you ever get build logs)
]

[start]
cmd = "dotnet dotnet-out/SelfQuest.dll"
